name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feat*
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "README.md"
  repository_dispatch: 

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["10", "8"]
    name: Node ${{ matrix.node }} Sample
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm build --if-present
      - run: npm test